$sublimeRoot = "C:\st"

Import-Module "$PSScriptRoot\SyntaxHelper.psm1"

Describe "Syntax highlighting" {
    
    if (-not (Test-Path $scopesFile)) {
        Write-Warning @'
This Pester UT file consumes scopes generated by python unit test Test_TokenGenerator.testGetTokens .
You need to run python tests first to make it work.
'@
        return
    }

    Context "test-file.ps1" {
        
        $scopesFile = Join-Path $sublimeRoot "Data\Packages\User\UnitTesting\tokens\PowerShell_tokens"
        $testFile = Resolve-Path "$PSScriptRoot\..\samples\test-file.ps1"

        # splitted in two lines, because of a bug in Sort-Object
        $stScopes = cat -Raw $scopesFile | ConvertFrom-Json; $stScopes = $stScopes | sort -Property @('startOffset', 'endOffset')
        # tokens are already sorted
        $psScopes = Get-TokensFromFile $testFile | Convert-TokenToScope 

        It "split tokens across the scopes 0 times" {
            $stIndex = 0
            $errorCounter = 0

            $psScopes | %{
                while ($stScopes[$stIndex].endOffset -le $_.startOffset) {
                    $stIndex++
                }

                $stScope = $stScopes[$stIndex]
                $psScope = $_

                #Write-Host "PowerShell scope $psScope"
                #Write-Host "SublimeText scope $stScope"
                
                if (-not (Test-ScopeInclosure $psScope $stScope)) {
                    #Write-Host "PowerShell scope $psScope not found in SublimeText scopes"
                    if (-not (Test-ScopeDisclosure $psScope $stScope)) {
                        $ignore = $false
                        
                        # These are minor things
                        if (@('$', '${', '-', '<#', '($') -contains $stScope.Text) {
                            $ignore = $true
                        }

                        # These are bugs, TODO it
                        if (@('Number', 'Redirection') -contains $psScope.Kind) {
                            $ignore = $true    
                        }

                        if (-not $ignore) {
                            Write-Warning "PowerShell scope $psScope overlap with SublimeText scope $stScope"
                            $errorCounter++
                        }
                    }
                }
            }
            $errorCounter | Should be @(0..4)
        }
    }
}