$sublimeRoot = "C:\st"

Import-Module "$PSScriptRoot\SyntaxHelper.psm1"

Describe "Syntax highlighting" {
    
    Context "test-file.ps1" {
        
        $tokensFolder = Join-Path $sublimeRoot "Data\Packages\User\UnitTesting\tokens" 
        $scopesFile = Join-Path $tokensFolder "test-file.ps1.tokens" 

        $testFile = Resolve-Path "$PSScriptRoot\..\samples\test-file.ps1"

        if (-not (Test-Path $scopesFile)) {
            Write-Warning 'This Pester UT suite consumes scopes generated by python unit test Test_TokenGenerator. You need to run python tests first.'
            return
        }

        # splitted in two lines, because of a bug in Sort-Object
        $stScopes =  Get-SublimeScopesFromFile $scopesFile
        # tokens are already sorted
        $psScopes = Get-TokensFromFile $testFile | Convert-TokenToScope 

        It "split tokens across the scopes 0 times" {
            $stIndex = 0
            $errorCounter = 0

            foreach ($psScope in $psScopes) {
                while ($stScopes[$stIndex].endOffset -le $psScope.startOffset) {
                    $stIndex++
                    if ($stIndex -ge $stScopes.Length) {
                        break
                    }
                }

                if ($stIndex -ge $stScopes.Length) {
                    # we are done with sublime scopes
                    break
                }

                $stScope = $stScopes[$stIndex]

                #Write-Host "PowerShell scope $psScope"
                #Write-Host "SublimeText scope $stScope"
                
                if (-not (Test-ScopeInclosure $psScope $stScope)) {
                    #Write-Host "PowerShell scope $psScope not found in SublimeText scopes"
                    if (-not (Test-ScopeDisclosure $psScope $stScope)) {
                        $ignore = $false
                        
                        # These are minor things
                        if (@('$', '${', '-', '<#', '($') -contains $stScope.Text) {
                            $ignore = $true
                        }

                        if (@('7>') -contains $psScope.Text) {
                            # this is fine. It's more like a powershell parsing problem.
                            $ignore = $true
                        }


                        # TODO: These are bugs
                        if (@('Number', 'Redirection') -contains $psScope.Kind) {
                            $ignore = $true    
                        }

                        if (-not $ignore) {
                            Write-Warning "PowerShell scope $psScope overlap with SublimeText scope $stScope"
                            $errorCounter++
                        }
                    }
                }
            }
            # TODO: These are bugs, make it 0
            $errorCounter | Should be 1
        }

        It "produces same tokens for lower case" {
            $stOtherScopes = Get-SublimeScopesFromFile (Join-Path $tokensFolder "test-file.ps1.lower.tokens" )
            Write-Host -ForegroundColor Cyan "Scopes count = $($stScopes.Length) "
            Write-Host -ForegroundColor Cyan "Lower scopes count = $($stOtherScopes.Length) "
            
            $n = @($stScopes.Length, $stOtherScopes.Length) | Get-Max
            0..($n-1) | % { 
                if (-not (Test-ScopesEqual $stScopes[$_] $stOtherScopes[$_])) {
                    #Write-Warning "Scopes are different $($stScopes[$_]) $($stOtherScopes[$_])"
                    $stScopes[$_] | Should be $stOtherScopes[$_]
                }
            }
        }

        It "produces same tokens for upper case" {
            $stOtherScopes = Get-SublimeScopesFromFile (Join-Path $tokensFolder "test-file.ps1.upper.tokens" )
            Write-Host -ForegroundColor Cyan "Scopes count = $($stScopes.Length) "
            Write-Host -ForegroundColor Cyan "Upper scopes count = $($stOtherScopes.Length) "

            $n = @($stScopes.Length, $stOtherScopes.Length) | Get-Max
            0..($n-1) | % { 
                if (-not (Test-ScopesEqual $stScopes[$_] $stOtherScopes[$_])) {
                    #Write-Warning "Scopes are different $($stScopes[$_]) $($stOtherScopes[$_])"
                    $stScopes[$_] | Should be $stOtherScopes[$_]
                }
            }
        }
    }
}