name: Package Review
# https://github.com/kaste/st_package_reviewer/tree/main/gh_action_package

on:
  workflow_dispatch:

jobs:
  package-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          # Repository checks inspect tags; the checkout action does not fetch
          # them by default for shallow clones.
          fetch-tags: true

      - name: Review this package repository
        uses: kaste/st_package_reviewer/gh_action_package@v1
